### ISSUE TITLE
Packed Inventory double Shulker Box support

### ISSUE THREAD

**Issue by sternschnaube** [Minecraft-AMS/Carpet-AMS-Addition#81]
### Motivation

/

### Description

https://modrinth.com/mod/packed-inventory
https://github.com/Kir-Antipov/packed-inventory

I am not able to access the double sized Shulker inventory with key press.

**Comment by 1024-byteeeee** [comment]
This is an issue related to container preview implementation. You should submit an issue to packed-inventory.

**Comment by 1024-byteeeee** [comment]
This is an issue related to container preview implementation. You should submit an issue to packed-inventory, However, I don't think this can be considered a bug. 🤔

**Comment by sternschnaube** [comment]
@Kir-Antipov please help us 😄

**Comment by sternschnaube** [comment]
Still not fixed(!), but I understand that you close it on this end.

**Comment by 1024-byteeeee** [comment]
> 仍然没有修复（！），但我知道你在这方面关闭了它。

It's not my problem bro

**Comment by Kir-Antipov** [comment]
> It's not my problem bro

It is tho :D

> This is an issue related to container preview implementation.

And you are absolutely right here! However, there is no "container preview implementation" on my side. And there is on yours ;)

By default, Packed Inventory uses vanilla `ShulkerBoxScreenHandler`, as it should. The problem is that this mod employs custom `largeShulkerBoxScreenHandler` without informing the game of its existence. The only thing it does is hijacking the screen handler creation logic in the `ShulkerBoxBlockEntity` class, as seen here:

https://github.com/Minecraft-AMS/Carpet-AMS-Addition/blob/aca4bd757f0f04c74a618112ce2a860bdfa08df8/src/main/java/club/mcams/carpet/mixin/rule/largeShulkerBox/ShulkerBoxBlockEntityMixin.java#L99-L104

This implementation is just a poor design decision in terms of compatibility with other shulker box-related mods:

1) Anyone attempting to open a shulker box screen without a shulker box present in its block in the world will end up with the wrong screen, affecting everything from Packed Inventory to someone trying to implement a shulker box minecart.
2) It does not respect patches that people make to `ShulkerBoxScreenHandler` because the mod ditches it entirely.

Instead of this, I propose completely nuking `largeShulkerBoxScreenHandler` and replacing it with a proper `ShulkerBoxScreenHandler` mixin.

If that sounds ok and you are open to accepting a PR, I can help with the implementation.

**Comment by sternschnaube** [comment]
Thank you for the clarification.

I hope for a great solution on both ends 😄

**Comment by 1024-byteeeee** [comment]
> > It's not my problem bro
> 
> 
> 
> It is tho :D
> 
> 
> 
> > This is an issue related to container preview implementation.
> 
> 
> 
> And you are absolutely right here! However, there is no "container preview implementation" on my side. And there is on yours ;)
> 
> 
> 
> By default, Packed Inventory uses vanilla `ShulkerBoxScreenHandler`, as it should. The problem is that this mod employs custom `largeShulkerBoxScreenHandler` without informing the game of its existence. The only thing it does is hijacking the screen handler creation logic in the `ShulkerBoxBlockEntity` class, as seen here:
> 
> 
> 
> https://github.com/Minecraft-AMS/Carpet-AMS-Addition/blob/aca4bd757f0f04c74a618112ce2a860bdfa08df8/src/main/java/club/mcams/carpet/mixin/rule/largeShulkerBox/ShulkerBoxBlockEntityMixin.java#L99-L104
> 
> 
> 
> This implementation is just a poor design decision in terms of compatibility with other shulker box-related mods:
> 
> 
> 
> 1) Anyone attempting to open a shulker box screen without a shulker box present in its block form in the world will end up with the wrong screen, affecting everything from Packed Inventory to someone trying to implement a shulker box minecart.
> 
> 2) It does not respect patches that people make to `ShulkerBoxScreenHandler` because the mod ditches it entirely.
> 
> 
> 
> Instead of this, I propose completely nuking `largeShulkerBoxScreenHandler` and replacing it with a proper `ShulkerBoxScreenHandler` mixin.
> 
> 
> 
> If that sounds ok and you are open to accepting a PR, I can help with the implementation.

You're right, I didn't consider the possibility of accommodating mods that allow previewing the contents of the shulker boxes when I implemented this rule 😂. My goal was just to make it larger. Your suggestion sounds great, and I'd be more than happy to accept the PR if you're willing to contribute.😋
